# Generated by Django 4.0.4 on 2022-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='directores',
            field=models.ManyToManyField(to='api.director'),
        ),
    ]
